#!/bin/bash
#SBATCH --job-name=CRESNEW-5-min-FEP
#SBATCH --output=mpi_%j.out 
#SBATCH --error=mpi_%j.err 
#SBATCH --ntasks=1 
#SBATCH --cpus-per-task=40 
#SBATCH --ntasks-per-node=1 
#SBATCH --ntasks-per-socket=1 
#SBATCH --gres=gpu:1 
  
module load python/3.6.5 boost/1.69.0 pnetcdf/1.11.2 amber/AMBERver 


pmemd.cuda -i min.in -c ti.inpcrd -p ti.prmtop -O -o min.out -inf min.info -e min.en -r min.rst -l min.log
sbatch FEP_EQUIL.cmd

